### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by faircloughS** [cBioPortal/oncoprintjs#19]
Hi I am having trouble installing oncoprintjs on my macbook pro. I have tried installing oncoprintjs on my Mac and in a docker running unbuntu and keep getting the same error. I don't think it is an oncoprintjs error per se, but a problem with the installation. Any guidance is appreciated.

gulp spec
[09:16:58] Using gulpfile ~/oncoprintjs/gulpfile.js
[09:16:58] Starting 'spec'...
[09:16:58] 'spec' errored after 31 ms
[09:16:58] Error in plugin 'gulp-jasmine'
Message:
    Cannot find module '../../src/js/sorting.js'
Details:
    code: MODULE_NOT_FOUND

**Comment by kretep** [comment]
I can confirm this also. The cause seems to be that some files were moved from `src/js/` to `src/.js/`and possible workarounds are either to move all files from the .js folder back to js or to correct the locations of `sorting.js`, `utils.js` and `main.js` in `sorting_spec.js`, `utils_spec.js` and `gulpfile.js` respectively.

**Comment by faircloughS** [comment]
I am gald it wasn't just me, but the proposed solution didn't seem to work. After moving all the files in the .js folder to the js folder I get the following errors:

gulp spec
[14:27:12] Using gulpfile ~/oncoprintjs/gulpfile.js
[14:27:12] Starting 'spec'...
....FFFFFF

Failures: 
1) is sample genetically altered shows that an empty sample (no data) is not genetically altered
1.1) TypeError: undefined is not a function

2) is sample genetically altered shows that a clinical-ish sample is not genetically altered
2.1) TypeError: undefined is not a function

3) is sample genetically altered shows that a genetically altered sample as altered
3.1) TypeError: undefined is not a function

4) validate_row_against_rows error if lengths don't match
4.1) Expected function to throw 'Row lengths don't match: 2 and 3', but it threw TypeError: undefined is not a function.
4.2) Expected function to throw 'Row lengths don't match: 3 and 2', but it threw TypeError: undefined is not a function.
4.3) Expected function to throw 'Rows are empty', but it threw TypeError: undefined is not a function.

5) validate_row_against_rows error if samples don't match up exactly
5.1) Expected function to throw 'Sample ids do not match between new row and given rows.', but it threw TypeError: undefined is not a function.
5.2) Expected function to throw 'Sample ids do not match between new row and given rows.', but it threw TypeError: undefined is not a function.

6) validate_row_against_rows returns true if all is well
6.1) TypeError: undefined is not a function

10 specs, 6 failures
Finished in 0 seconds
[14:27:12] 'spec' errored after 71 ms
[14:27:12] Error in plugin 'gulp-jasmine'
Message:
    Tests failed

Again, any guidance is appreciated.

**Comment by kretep** [comment]
I agree it's strange that the unit tests fail, but I got it running anyway after running `gulp test` (to generate the test data) and accessing the index.html through http-server.

I started a discussion in the cbioportal google group; maybe there will be further clues: https://groups.google.com/forum/#!topic/cbioportal/3J8OTanYRxg

**Comment by binhudakhalid** [comment]
khalid@FLUX-ProBook:~/Dev/goc/oncoprintjs/src$ gulp test
[19:44:07] Using gulpfile ~/Dev/goc/oncoprintjs/src/gulpfile.js
[19:44:07] Starting 'test'...
Error: Cannot find module 'gl-matrix' from '/home/khalid/Dev/goc/oncoprintjs/src'
    at /usr/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/usr/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/usr/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/usr/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /usr/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:123:15)
[19:44:07] 'test' errored after 607 ms
[19:44:07] Error in plugin 'gulp-shell'
Message:
    Command `browserify test.js -o oncoprint-test-bundle.js` failed with exit code 1
